import type { Metadata } from "next";
import { Toaster } from "sonner";
import localFont from "next/font/local";
import "./globals.css";

const sfPro = localFont({
  src: [
    {
      path: "./fonts/SFProDisplay-Medium.woff2",
      weight: "500",
    },
    {
      path: "./fonts/SFProDisplay-Regular.woff2",
      weight: "400",
    },
    {
      path: "./fonts/SFProDisplay-Bold.woff2",
      weight: "700",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={sfPro.className}>
        <Toaster richColors />
        {children}
      </body>
    </html>
  );
}
